#include "monty.h"

/**
 * div_ - divides the top two elements in the stack and sets the result on the
 * stack, after popping the top two elements
 * @stack: the stack generated by the monty bytecode @file
 * @ln: line number of monty f currently being processed
 * Return: void
 */
void div_(stack_t **stack, unsigned int ln)
{
	int quotient;

	if (!*stack || !(*stack)->next || (*stack)->n == 0)
	{
		if ((*stack)->n == 0)
			fprintf(stderr, "L%d: division by zero\n", ln);
		else
			fprintf(stderr, "L%d: can't div, stack too short\n", ln);
		fclose(file);
		exit(EXIT_FAILURE);
	}

	quotient = (*stack)->next->n / (*stack)->n;
	pop(stack, ln);
	pop(stack, ln);
	add_dnodeint(stack, quotient);
}
