#include "monty.h"

/**
 * mul - multiplies the top two elements in the stack and sets the result on the
 * stack, after popping the top two elements
 * @stack: the stack generated by the monty bytecode @file
 * @ln: line number of monty f currently being processed
 * Return: void
 */
void mul(stack_t **stack, unsigned int ln)
{
	int result;

	if (!*stack || !(*stack)->next)
	{
		fprintf(stderr, "L%d: can't mul, stack too short\n", ln);
		fclose(file);
		exit(EXIT_FAILURE);
	}

	result = (*stack)->n + (*stack)->next->n;
	pop(stack, ln);
	pop(stack, ln);
	add_dnodeint(stack, result);
}
