#include "monty.h"

/**
 * pop - deletes the number on the top of the stack
 * @stack: the stack generated by the monty bytecode @file
 * @ln: line number currently being operated on @file
 */
void pop(stack_t **stack, int ln)
{
	stack_t *new_head;

	if (!*stack)
	{
		fprintf(stderr, "L%d: can't pop an empty stack\n", ln);
		fclose(file);
		exit(EXIT_FAILURE);
	}

	new_head = (*stack)->next;
	*stack = NULL;
	if (*stack)
		free(*stack);
	*stack = new_head;
}
